package dev.behradhz.meowzix.data.db

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class MigrationTest {
    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        MeowzixDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory(),
    )

    @Test
    fun migrateOneToTwoAddsContentUriUniqueness() {
        helper.createDatabase(TEST_DATABASE_1_2, 1).close()
        helper.runMigrationsAndValidate(TEST_DATABASE_1_2, 2, true, MIGRATION_1_2).close()
    }

    @Test
    fun migrateTwoToThreeAddsTelegramSourceStorage() {
        helper.createDatabase(TEST_DATABASE_2_3, 2).close()
        helper.runMigrationsAndValidate(TEST_DATABASE_2_3, 3, true, MIGRATION_2_3).close()
    }

    @Test
    fun migrateThreeToFourAddsOfflineDownloadStorage() {
        helper.createDatabase(TEST_DATABASE_3_4, 3).close()
        helper.runMigrationsAndValidate(TEST_DATABASE_3_4, 4, true, MIGRATION_3_4).close()
    }

    @Test
    fun migrateFourToFiveAddsPlaylistStorage() {
        helper.createDatabase(TEST_DATABASE_4_5, 4).close()
        helper.runMigrationsAndValidate(TEST_DATABASE_4_5, 5, true, MIGRATION_4_5).close()
    }

    @Test
    fun migrateFiveToSixAddsListeningHistoryStorage() {
        helper.createDatabase(TEST_DATABASE_5_6, 5).close()
        helper.runMigrationsAndValidate(TEST_DATABASE_5_6, 6, true, MIGRATION_5_6).close()
    }

    @Test
    fun migrateSixToEightAddsCanonicalAudioFeatureStorage() {
        helper.createDatabase(TEST_DATABASE_6_8, 6).close()
        helper.runMigrationsAndValidate(
            TEST_DATABASE_6_8,
            8,
            true,
            MIGRATION_6_7,
            MIGRATION_7_8,
        ).close()
    }

    @Test
    fun migrateSevenToEightRepairsDerivedFeatureTableAndPreservesTracks() {
        val database = helper.createDatabase(TEST_DATABASE_7_8_REPAIR, 6)
        database.execSQL(
            "INSERT INTO `tracks` (`id`, `title`, `normalizedTitle`, `artist`, `normalizedArtist`, `album`, " +
                "`durationMs`, `trackNumber`, `year`, `artworkRef`, `favorite`, `hidden`, `createdAtEpochMs`, `updatedAtEpochMs`) " +
                "VALUES ('repair-track', 'Repair Track', 'repair track', NULL, NULL, NULL, 1000, NULL, NULL, NULL, 0, 0, 1, 1)",
        )
        MIGRATION_6_7.migrate(database)
        database.execSQL("DROP TABLE `audio_feature_vectors`")
        database.execSQL(
            "CREATE TABLE `audio_feature_vectors` (`id` TEXT NOT NULL, `legacyPayload` TEXT, PRIMARY KEY(`id`))",
        )
        database.version = 7
        database.close()

        val migrated = helper.runMigrationsAndValidate(
            TEST_DATABASE_7_8_REPAIR,
            8,
            true,
            MIGRATION_7_8,
        )
        migrated.query("SELECT `id` FROM `tracks` WHERE `id` = 'repair-track'").use { cursor ->
            assertTrue(cursor.moveToFirst())
        }
        migrated.close()
    }

    @Test
    fun migrateTenToElevenAddsTelegramSendQueue() {
        // Schema 11 was generated by the historical CI build but was never committed to source.
        // Exercise the migration directly from the committed schema-10 fixture instead of silently
        // skipping this regression test because MigrationTestHelper cannot load a missing 11.json.
        val database = helper.createDatabase(TEST_DATABASE_10_11, 10)
        MIGRATION_10_11.migrate(database)
        database.version = 11

        database.query("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'telegram_send_jobs'").use { cursor ->
            assertTrue(cursor.moveToFirst())
        }
        listOf(
            "index_telegram_send_jobs_trackId",
            "index_telegram_send_jobs_state",
            "index_telegram_send_jobs_activeDedupeKey",
        ).forEach { indexName ->
            database.query(
                "SELECT name FROM sqlite_master WHERE type = 'index' AND name = ?",
                arrayOf(indexName),
            ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        }
        database.close()
    }

    @Test
    fun migrateElevenToTwelveBackfillsUnicodeFtsAndCandidateIndexes() {
        // Reconstruct a real version-11 database from the committed v10 schema + the production
        // 10->11 migration. This keeps 11->12 coverage valid without fabricating schema history.
        val database = helper.createDatabase(TEST_DATABASE_11_12, 10)
        MIGRATION_10_11.migrate(database)
        database.version = 11
        database.execSQL(
            "INSERT INTO `tracks` (`id`, `title`, `normalizedTitle`, `artist`, `normalizedArtist`, `album`, " +
                "`durationMs`, `trackNumber`, `year`, `artworkRef`, `favorite`, `hidden`, `createdAtEpochMs`, `updatedAtEpochMs`) " +
                "VALUES ('english-track', 'Radiohead Song', 'radiohead song', 'Radiohead', 'radiohead', 'Album', 180000, NULL, NULL, NULL, 0, 0, 1, 1)",
        )
        database.execSQL(
            "INSERT INTO `tracks` (`id`, `title`, `normalizedTitle`, `artist`, `normalizedArtist`, `album`, " +
                "`durationMs`, `trackNumber`, `year`, `artworkRef`, `favorite`, `hidden`, `createdAtEpochMs`, `updatedAtEpochMs`) " +
                "VALUES ('persian-track', 'موسیقی شب', 'موسیقی شب', 'هنرمند', 'هنرمند', 'آلبوم', 200000, NULL, NULL, NULL, 0, 0, 1, 1)",
        )
        // v12 was never committed; only the current v13 schema is generated by a clean build.
        MIGRATION_11_12.migrate(database)
        database.version = 12
        val migrated = database

        migrated.query(
            "SELECT name FROM sqlite_master WHERE type = 'index' " +
                "AND name = 'index_tracks_normalizedTitle_normalizedArtist_durationMs'",
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type = 'index' " +
                "AND name = 'index_track_sources_contentHashSha256'",
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT trackId FROM track_search_fts WHERE track_search_fts MATCH ?",
            arrayOf("\"radio*\""),
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("english-track", cursor.getString(0))
        }
        migrated.query(
            "SELECT trackId FROM track_search_fts WHERE track_search_fts MATCH ?",
            arrayOf("\"موسی*\""),
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("persian-track", cursor.getString(0))
        }
        migrated.close()
    }

    @Test
    fun migrateTwelveToThirteenPreservesLibraryAndAddsCanonicalTrainingSamples() {
        // As with v11/v12, schema 13 was historically generated in CI but not committed. Rebuild
        // the real v12 state from the committed v10 fixture, then exercise the production migration
        // directly instead of requiring a fabricated 13.json validation fixture.
        val database = helper.createDatabase(TEST_DATABASE_12_13, 10)
        MIGRATION_10_11.migrate(database)
        MIGRATION_11_12.migrate(database)
        database.execSQL("INSERT INTO tracks (id, title, normalizedTitle, durationMs, favorite, hidden, createdAtEpochMs, updatedAtEpochMs) VALUES ('kept', 'Kept', 'kept', 100000, 1, 0, 1, 1)")
        database.version = 12

        MIGRATION_12_13.migrate(database)
        database.version = 13
        val migrated = database

        migrated.query("SELECT favorite FROM tracks WHERE id = 'kept'").use {
            assertTrue(it.moveToFirst()); assertEquals(1, it.getInt(0))
        }
        migrated.query("PRAGMA table_info(training_samples)").use { assertEquals(12, it.count) }
        migrated.query("PRAGMA foreign_key_list(training_samples)").use { assertTrue(it.moveToFirst()) }
        migrated.query("SELECT name FROM sqlite_master WHERE name = 'index_training_samples_dataVersion'").use { assertTrue(it.moveToFirst()) }
        migrated.close()
    }

    @Test
    fun migrateThirteenToFourteenPreservesLibraryAndAddsVersionedLyrics() {
        // Reconstruct v13 from the last committed schema fixture so this regression test stays
        // meaningful even though intermediate schema JSON files were historically not committed.
        val database = helper.createDatabase(TEST_DATABASE_13_14, 10)
        MIGRATION_10_11.migrate(database)
        MIGRATION_11_12.migrate(database)
        MIGRATION_12_13.migrate(database)
        database.execSQL(
            "INSERT INTO tracks (id, title, normalizedTitle, durationMs, favorite, hidden, createdAtEpochMs, updatedAtEpochMs) " +
                "VALUES ('lyrics-kept', 'Lyrics Kept', 'lyrics kept', 100000, 1, 0, 1, 1)",
        )
        database.version = 13

        MIGRATION_13_14.migrate(database)
        database.version = 14

        database.query("SELECT favorite FROM tracks WHERE id = 'lyrics-kept'").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(1, cursor.getInt(0))
        }
        database.query("PRAGMA table_info(lyrics_versions)").use { cursor ->
            assertEquals(11, cursor.count)
        }
        database.query("PRAGMA foreign_key_list(lyrics_versions)").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("tracks", cursor.getString(cursor.getColumnIndexOrThrow("table")))
        }
        listOf(
            "index_lyrics_versions_trackId",
            "index_lyrics_versions_trackId_selected",
        ).forEach { indexName ->
            database.query(
                "SELECT name FROM sqlite_master WHERE type = 'index' AND name = ?",
                arrayOf(indexName),
            ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        }
        database.close()
    }

    @Test
    fun migrateFifteenToSixteenAddsVersionedLoudnessAnalysis() {
        // Schema 15 was generated by CI while v15 was current but was not historically committed.
        // Reconstruct the real v15 database from the last committed v10 fixture, then let Room
        // validate only the production 15 -> 16 hop against the generated current (v16) schema.
        val database = helper.createDatabase(TEST_DATABASE_15_16, 10)
        MIGRATION_10_11.migrate(database)
        MIGRATION_11_12.migrate(database)
        MIGRATION_12_13.migrate(database)
        MIGRATION_13_14.migrate(database)
        MIGRATION_14_15.migrate(database)
        database.execSQL(
            "INSERT INTO tracks (id, title, normalizedTitle, durationMs, favorite, hidden, createdAtEpochMs, updatedAtEpochMs) " +
                "VALUES ('loudness-kept', 'Loudness', 'loudness', 100000, 0, 0, 1, 1)",
        )
        database.version = 15
        database.close()
        val migrated = helper.runMigrationsAndValidate(TEST_DATABASE_15_16, 16, true, MIGRATION_15_16)
        migrated.query("SELECT title FROM tracks WHERE id='loudness-kept'").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Loudness", cursor.getString(0))
        }
        migrated.query("PRAGMA table_info(loudness_analyses)").use { cursor -> assertEquals(12, cursor.count) }
        migrated.query("PRAGMA foreign_key_list(loudness_analyses)").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("tracks", cursor.getString(cursor.getColumnIndexOrThrow("table")))
        }
        migrated.close()
    }

    private companion object {
        const val TEST_DATABASE_1_2 = "migration-test-1-2"
        const val TEST_DATABASE_2_3 = "migration-test-2-3"
        const val TEST_DATABASE_3_4 = "migration-test-3-4"
        const val TEST_DATABASE_4_5 = "migration-test-4-5"
        const val TEST_DATABASE_5_6 = "migration-test-5-6"
        const val TEST_DATABASE_6_8 = "migration-test-6-8"
        const val TEST_DATABASE_7_8_REPAIR = "migration-test-7-8-repair"
        const val TEST_DATABASE_10_11 = "migration-test-10-11"
        const val TEST_DATABASE_11_12 = "migration-test-11-12"
        const val TEST_DATABASE_12_13 = "migration-test-12-13"
        const val TEST_DATABASE_13_14 = "migration-test-13-14"
        const val TEST_DATABASE_15_16 = "migration-test-15-16"
    }
}
